com.bmuschko:gradle-tomcat-plugin:2.2.5
```
build.gradle:
tomcat {
    enableSSL = true
    // enableSSL = false
}
```

$ ./gradlew tomcatRun
:chapter01:chapter01.00-calendar:compileJava NO-SOURCE
:chapter01:chapter01.00-calendar:processResources NO-SOURCE
:chapter01:chapter01.00-calendar:classes UP-TO-DATE
:chapter01:chapter01.00-calendar:tomcatRun

Warning:
The JKS keystore uses a proprietary format. It is recommended to migrate
to PKCS12 which is an industry standard format using "keytool
-importkeystore -srckeystore ${projectDir}\build\tmp\ssl\keystore
-destkeystore ${projectDir}\build\tmp\ssl\keystore -deststoretype
pkcs12".

A child container failed during start
java.util.concurrent.ExecutionException:
org.apache.catalina.LifecycleException: Failed to start component
[StandardEngine[Tomcat].StandardHost[localhost].StandardContext[]]
  at java.util.concurrent.FutureTask.report(FutureTask.java:122)
  at java.util.concurrent.FutureTask.get(FutureTask.java:192)
  ... 2 more
  at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
  at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.)
  ... 5 more
Caused by: org.apache.catalina.LifecycleException: Failed to initialize
component [org.apache.catalina.webresources.StandardRoot@13ee9d5]
  at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:107)
  ... 10 more
  at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
  ... 6 more
Caused by: java.lang.Error: factory already defined
  at java.net.URL.setURLStreamHandlerFactory(URL.java:1112)
  at org.apache.catalina.webresources.TomcatURLStreamHandlerFactory.<init>(TomcatURLStreamHandlerFactory.java:130)
  ... 4 more
  at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:102)
  ... 10 more
A child container failed during start
java.util.concurrent.ExecutionException:
org.apache.catalina.LifecycleException: Failed to start component
[StandardEngine[Tomcat].StandardHost[localhost]]
  at java.util.concurrent.FutureTask.report(FutureTask.java:122)
  at java.util.concurrent.FutureTask.get(FutureTask.java:192)
  ... + more
  at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
  ... 6 more
:chapter01:chapter01.00-calendar:tomcatRun FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':chapter01:chapter01.00-calendar:tomcatRun'.
> An error occurred starting the Tomcat server.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or
--debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s
1 actionable task: 1 executed